name: Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout Github Action'
        uses: actions/checkout@master
      
      - name: 'ACR Login'          
      - uses: docker-login@v1
        with: 
          login-server: 'acrreserve.azurecr.io'
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.RESISTRY_PASSWORD }}
          
      - name: 'Build and Push'
      - run: |
          docker build . -t acrreserve.azurecr.io/lossdevt:${{ github.sha }}
          docker push acrreserve.azurecr.io/lossdevt:${{ github.sha }}
          
      - name: 'Deploy WebApp'
        uses: azure/webapps-deply@v2
        with:
          app-name: 'lossdevt'
          publish-profile: ${{ secrets.azureWebAppPublishProfile }}
          images: 'acrreserve.azurecr.io/lossdevt:${{ github.sha }}'
