# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - lossdevt

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: https://ghcr.io/
          username: ${{ secrets.AzureAppService_ContainerUsername_706b5aaf9b0b478b859b532a73fd149f }}
          password: ${{ secrets.AzureAppService_ContainerPassword_98f43731d7d1407f9088742224d33d83 }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ghcr.io/${{ secrets.AzureAppService_ContainerUsername_706b5aaf9b0b478b859b532a73fd149f }}/ghcr.io/jimbrig-work/lossdevt:${{ github.sha }}
          file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'lossdevt'
          slot-name: 'production'
          publish-profile: ${{ secrets.AzureAppService_PublishProfile_49c7a0ff87ab475a8c1ee4dcae0aece9 }}
          images: 'ghcr.io/${{ secrets.AzureAppService_ContainerUsername_706b5aaf9b0b478b859b532a73fd149f }}/ghcr.io/jimbrig-work/lossdevt:${{ github.sha }}'
